routes/web.php
<?php

// use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'census-operation', 'namespace' => 'CensusOperation', 'as' => 'census-operation.'], function () {
        Route::group(['prefix' => 'edoc1-management', 'namespace' => 'Edoc1Management', 'as' => 'edoc1-management.'], function () {

            Route::get('edoc1-verifications', 'Edoc1VerificationController@index')->name('edoc1-verifications.index');
            Route::get('edoc1-verifications/{edoc1_verification}', 'Edoc1VerificationController@show')->name('edoc1-verifications.show');
            Route::get('edoc1-verifications/{edoc1_verification}/detail', 'Edoc1VerificationController@detail')->name('edoc1-verifications.detail');
            Route::get('edoc2-verifications/{edoc2_verification}', 'Edoc2VerificationController@index')->name('edoc2-verifications.index');

        });
    });


    Route::resource('dashboard', 'DashboardController');
    Route::get('/', 'DashboardController@index')->name('dashboard');

});

\Auth::routes();

Route::any('logout', 'Auth\LoginController@logout');


Route::get('media/{id}', function ($id) {

    $media = \Spatie\MediaLibrary\Models\Media::find($id);

    if (!$media) {
        return response()->file(public_path('images/no-product-image.png'));
    }

    if ($conversion = request()->input('conversion', null)) {
        return response()->file($media->getPath($conversion));

    }

    return response()->file($media->getPath());

})->name('media.show');

Route::get('/personal', function () {
    return view('Co_Management.cati_officer.personal_info');
});

Route::get('/personal2', function () {
    return view('Co_Management.cati_officer.personal_info2');
})->name('personal2');

Route::get('create-chart/{type}','ChartController@makeChart');

Route::get('/assignjob', function () {
    return view('Co_Management.job_assignment.assign_job');
});

Route::get('/total_household', function () {
    return view('eRKL.total_household');
});

Route::get('/summary_household_state', function () {
    return view('eRKL.summary_household_state');
});

Route::get('/edoc24', function () {
    return view('eRKL.edoc24');
});

Route::get('householdST', 'HouseholdController@index')->name('householdST');
Route::get('householdAD', 'HouseholdController@householdAD')->name('householdAD');
Route::get('householdCD', 'HouseholdController@householdCD')->name('householdCD');
Route::get('householdCC', 'HouseholdController@householdCC')->name('householdCC');
Route::get('householdEB', 'HouseholdController@householdEB')->name('householdEB');

Route::get('genderST', 'GenderController@index')->name('genderST');
Route::get('genderEB', 'GenderController@genderEB')->name('genderEB');
Route::get('genderCC', 'GenderController@genderCC')->name('genderCC');
Route::get('genderCD', 'GenderController@genderCD')->name('genderCD');
Route::get('genderAD', 'GenderController@genderAD')->name('genderAD');

Route::get('worklist_edoc24', 'WorklistController@index')->name('worklist_edoc24');
Route::post('worklist_update', 'WorklistController@update')->name('worklist_update');
Route::get('edoc24', 'WorklistController@edoc24')->name('edoc24');
Route::get('/getPDF','WorklistController@getPDF')->name('getPDF');
Route::get('dynamic_pdf','DynamicPDFController@index');
Route::get('dynamic_pdf/pdf','DynamicPDFController@pdf');

Route::get('barchart_compare', 'HouseholdController@barchartCompare')->name('barchart_compare');

Route::get('/citizenship_state', function () {
    return view('eRKL.citizenship_state');
});

Route::get('/citizenship_ad', function () {
    return view('eRKL.citizenship_ad');
});

Route::get('/citizenship_cd', function () {
    return view('eRKL.citizenship_cd');
});

Route::get('/citizenship_cc', function () {
    return view('eRKL.citizenship_cc');
});

Route::get('/citizenship_eb', function () {
    return view('eRKL.citizenship_eb');
});

Route::get('/etnicity_state', function () {
    return view('eRKL.etnicity_state');
});

Route::get('/etnicity_ad', function () {
    return view('eRKL.etnicity_ad');
});

Route::get('/etnicity_cd', function () {
    return view('eRKL.etnicity_cd');
});

Route::get('/etnicity_cc', function () {
    return view('eRKL.etnicity_cc');
});

Route::get('/etnicity_eb', function () {
    return view('eRKL.etnicity_eb');
});

app/Http/Controllers/CensusOperation/Edoc1Management/BaseController.php
<?php namespace App\Http\Controllers\CensusOperation\Edoc1Management;

class BaseController extends \App\Http\Controllers\CensusOperation\BaseController
{
    public function __construct()
    {
        parent::__construct();
    }
}

app/Http/Controllers/CensusOperation/Edoc1Management/Edoc1VerificationController.php
<?php namespace App\Http\Controllers\CensusOperation\Edoc1Management;


use App\EnumerationBlock;
use App\Household;
use App\HouseholdMember;
use App\LivingQuarter;
use App\Setting;

class Edoc1VerificationController extends BaseController
{
    protected $baseRoute = 'census-operation.edoc1-management.edoc1-verifications';
    protected $baseView = 'census_operation.edoc1_management.edoc1_verification';
//    protected $pageHeaderText = 'Pen';
//    protected $resourceName = 'Credit Package';

    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        $models=EnumerationBlock::get();
        return $this->view([$this->baseView, 'index'], compact('models'));
    }

    public function show($id)
    {
        $enumerationBlock=EnumerationBlock::find($id);
        $livingQuarters=$enumerationBlock->livingQuarters;
        $households=$enumerationBlock->households;
        $householdMembers=HouseholdMember::whereIn('household_id',$households->pluck('id')->toArray())->get();
        return $this->view([$this->baseView, 'show'], compact('enumerationBlock','households','livingQuarters','householdMembers'));
    }

    public function detail($id)
    {
        $household=Household::find($id);
        return $this->view([$this->baseView, 'detail'], compact('household'));
    }

}

app/Http/Controllers/CensusOperation/Edoc1Management/Edoc2VerificationController.php
<?php namespace App\Http\Controllers\CensusOperation\Edoc1Management;


use App\EnumerationBlock;
use App\Household;
use App\HouseholdMember;
use App\Setting;

class Edoc2VerificationController extends BaseController
{
    protected $baseRoute = 'census-operation.edoc1-management.edoc2-verifications';
    protected $baseView = 'census_operation.edoc1_management.edoc2_verification';
//    protected $pageHeaderText = 'Pen';
//    protected $resourceName = 'Credit Package';

    public function __construct()
    {
        parent::__construct();
    }

    public function index($id)
    {
        $household=Household::find($id);
        return $this->view([$this->baseView, 'index'], compact('household'));
    }

    public function show($id)
    {
        $enumerationBlock=EnumerationBlock::find($id);
        $livingQuarters=$enumerationBlock->livingQuarters;
        $households=$enumerationBlock->households;
        $householdMembers=HouseholdMember::whereIn('household_id',$households->pluck('id')->toArray())->get();
        return $this->view([$this->baseView, 'show'], compact('enumerationBlock','households','livingQuarters','householdMembers'));
    }

}

resources/views/census_operation/edoc1_management/edoc2_verification/index.blade.php
@extends('layouts.page_with_sidebar.main')
@section('content')
    <h1 class="page-header">Edoc 2  </h1>
    <div class="row">
        <div class="col-md-3">
            <div class="widget widget-stats bg-blue">
                <div class="stats-icon"><i class="fa fa-table"></i></div>
                <div class="stats-info">
                    <h4>Jumlah Isi Rumah</h4>
                    <p>{{$household->householdMembers()->count()}}</p>
                </div>
                <div class="stats-link">
{{--                    <a href="{{route($baseRoute.'.index',[])}}">Show all <i class="fa fa-arrow-alt-circle-right"></i></a>--}}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <i class="fa fa-user"></i>
                    Maklumat Tempat Kediaman
                    <div class="panel-heading-btn">

                    </div>
                </div>
                <div class="panel-body">

                </div>
            </div>
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <i class="fa fa-user"></i>
                    Maklumat Ketua Isi Rumah
                    <div class="panel-heading-btn">

                    </div>
                </div>
                <div class="panel-body">

                </div>
            </div>
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <i class="fa fa-user"></i>
                    Ringkasan Blok Penghitungan
                    <div class="panel-heading-btn">

                    </div>
                </div>
                <div class="panel-body">

                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <i class="fa fa-list"></i>
                    Senarai tempat kediaman mengikut kumpulan isi rumah
                    <div class="panel-heading-btn">
                        {{--@role('admin')--}}
                        {{--<a href="{{route($baseRoute.'.create')}}" class="btn btn-default btn-xs"><i class="fa fa-plus"></i> {{$resourceName}}</a>--}}
                        {{--@endrole--}}

                    </div>
                </div>
                <div class="panel-body">
                    <table width="100%" class="datatable table table-striped">
                        <thead>
                        <tr>
                            <td width="1%">ID</td>
                            <td>No. UB</td>
                            <td>No. TK/TKI/BTK</td>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($households as $index=>$item)
                            <tr>
                                <td>{{$item->id}}</td>
                                <td>{{$item->livingQuarter->living_quarter_information['ub_number']??'-'}}</td>
                                <td>{{$item->livingQuarter->living_quarter_information['living_quarter_number']??'-'}}</td>
                                <td align="right">
                                    <div style="white-space: nowrap">
                                        <a href="{{route('census-operation.edoc1-management.edoc2-verifications.index',[$item->id])}}" class="btn btn-info btn-xs" title="Perincian"><i class="fa fa-folder"></i></a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/census_operation/edoc1_management/edoc2_verification/show.blade.php
@extends('layouts.page_with_sidebar.main')
@section('content')
    <h1 class="page-header">Edoc 1  </h1>
    <div class="row">
        <div class="col-md-3">
            <div class="widget widget-stats bg-blue">
                <div class="stats-icon"><i class="fa fa-table"></i></div>
                <div class="stats-info">
                    <h4>Jumlah Tempat Kediaman</h4>
                    <p>{{$livingQuarters->count()}}</p>
                </div>
                <div class="stats-link">
                    {{--                    <a href="{{route($baseRoute.'.index',[])}}">Show all <i class="fa fa-arrow-alt-circle-right"></i></a>--}}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="widget widget-stats bg-blue">
                <div class="stats-icon"><i class="fa fa-table"></i></div>
                <div class="stats-info">
                    <h4>Jumlah Kumpulan Isi Rumah</h4>
                    <p>{{$households->count()}}</p>
                </div>
                <div class="stats-link">
                    {{--                    <a href="{{route($baseRoute.'.index',[])}}">Show all <i class="fa fa-arrow-alt-circle-right"></i></a>--}}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="widget widget-stats bg-blue">
                <div class="stats-icon"><i class="fa fa-table"></i></div>
                <div class="stats-info">
                    <h4>Jumlah Isi Rumah</h4>
                    <p>{{$householdMembers->count()}}</p>
                </div>
                <div class="stats-link">
                    {{--                    <a href="{{route($baseRoute.'.index',[])}}">Show all <i class="fa fa-arrow-alt-circle-right"></i></a>--}}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <i class="fa fa-user"></i>
                    Maklumat Pembanci
                    <div class="panel-heading-btn">

                    </div>
                </div>
                <div class="panel-body">

                </div>
            </div>
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <i class="fa fa-user"></i>
                    Butir Butir Pengenalan Blok Penghitungan
                    <div class="panel-heading-btn">

                    </div>
                </div>
                <div class="panel-body">

                </div>
            </div>
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <i class="fa fa-user"></i>
                    Ringkasan Blok Penghitungan
                    <div class="panel-heading-btn">

                    </div>
                </div>
                <div class="panel-body">

                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <i class="fa fa-list"></i>
                    Senarai tempat kediaman mengikut kumpulan isi rumah
                    <div class="panel-heading-btn">
                        {{--@role('admin')--}}
                        {{--<a href="{{route($baseRoute.'.create')}}" class="btn btn-default btn-xs"><i class="fa fa-plus"></i> {{$resourceName}}</a>--}}
                        {{--@endrole--}}

                    </div>
                </div>
                <div class="panel-body">
                    <table width="100%" class="datatable table table-striped">
                        <thead>
                        <tr>
                            <td width="1%">ID</td>
                            <td>No. UB</td>
                            <td>No. TK/TKI/BTK</td>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($households as $index=>$item)
                            <tr>
                                <td>{{$item->id}}</td>
                                <td>{{$item->livingQuarter->living_quarter_information['ub_number']??'-'}}</td>
                                <td>{{$item->livingQuarter->living_quarter_information['living_quarter_number']??'-'}}</td>
                                <td align="right">
                                    <div style="white-space: nowrap">
                                        <a href="{{route($baseRoute.'.show',[$item->id])}}" class="btn btn-info btn-xs" title="Perincian"><i class="fa fa-folder"></i></a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop