routes/web.php
<?php

// use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'census-operation', 'namespace' => 'CensusOperation', 'as' => 'census-operation.'], function () {
        Route::group(['prefix' => 'edoc1-management', 'namespace' => 'Edoc1Management', 'as' => 'edoc1-management.'], function () {

            Route::get('edoc1-verifications', 'Edoc1VerificationController@index')->name('edoc1-verifications.index');
            Route::get('edoc1-verifications/{edoc1_verification}', 'Edoc1VerificationController@show')->name('edoc1-verifications.show');
            Route::get('edoc1-verifications/{edoc1_verification}/detail', 'Edoc1VerificationController@detail')->name('edoc1-verifications.detail');
            Route::get('edoc2-verifications/{edoc2_verification}', 'Edoc2VerificationController@index')->name('edoc2-verifications.index');

        });
    });


    Route::resource('dashboard', 'DashboardController');
    Route::get('/', 'DashboardController@index')->name('dashboard');

});

\Auth::routes();

Route::any('logout', 'Auth\LoginController@logout');


Route::get('media/{id}', function ($id) {

    $media = \Spatie\MediaLibrary\Models\Media::find($id);

    if (!$media) {
        return response()->file(public_path('images/no-product-image.png'));
    }

    if ($conversion = request()->input('conversion', null)) {
        return response()->file($media->getPath($conversion));

    }

    return response()->file($media->getPath());

})->name('media.show');

Route::get('/personal', function () {
    return view('Co_Management.cati_officer.personal_info');
});

Route::get('/personal2', function () {
    return view('Co_Management.cati_officer.personal_info2');
})->name('personal2');

Route::get('create-chart/{type}','ChartController@makeChart');

Route::get('/assignjob', function () {
    return view('Co_Management.job_assignment.assign_job');
});

Route::get('/total_household', function () {
    return view('eRKL.total_household');
});

Route::get('/summary_household_state', function () {
    return view('eRKL.summary_household_state');
});

Route::get('/edoc24', function () {
    return view('eRKL.edoc24');
});

Route::get('householdST', 'HouseholdController@index')->name('householdST');
Route::get('householdAD', 'HouseholdController@householdAD')->name('householdAD');
Route::get('householdCD', 'HouseholdController@householdCD')->name('householdCD');
Route::get('householdCC', 'HouseholdController@householdCC')->name('householdCC');
Route::get('householdEB', 'HouseholdController@householdEB')->name('householdEB');

Route::get('genderST', 'GenderController@index')->name('genderST');
Route::get('genderEB', 'GenderController@genderEB')->name('genderEB');
Route::get('genderCC', 'GenderController@genderCC')->name('genderCC');
Route::get('genderCD', 'GenderController@genderCD')->name('genderCD');
Route::get('genderAD', 'GenderController@genderAD')->name('genderAD');

Route::get('worklist_edoc24', 'WorklistController@index')->name('worklist_edoc24');
Route::post('worklist_update', 'WorklistController@update')->name('worklist_update');
Route::get('edoc24', 'WorklistController@edoc24')->name('edoc24');
Route::get('/getPDF','WorklistController@getPDF')->name('getPDF');
Route::get('dynamic_pdf','DynamicPDFController@index');
Route::get('dynamic_pdf/pdf','DynamicPDFController@pdf');

Route::get('barchart_compare', 'HouseholdController@barchartCompare')->name('barchart_compare');

Route::get('/citizenship_state', function () {
    return view('eRKL.citizenship_state');
});

Route::get('/citizenship_ad', function () {
    return view('eRKL.citizenship_ad');
});

Route::get('/citizenship_cd', function () {
    return view('eRKL.citizenship_cd');
});

Route::get('/citizenship_cc', function () {
    return view('eRKL.citizenship_cc');
});

Route::get('/citizenship_eb', function () {
    return view('eRKL.citizenship_eb');
});

Route::get('/etnicity_state', function () {
    return view('eRKL.etnicity_state');
});

Route::get('/etnicity_ad', function () {
    return view('eRKL.etnicity_ad');
});

Route::get('/etnicity_cd', function () {
    return view('eRKL.etnicity_cd');
});

Route::get('/etnicity_cc', function () {
    return view('eRKL.etnicity_cc');
});

Route::get('/etnicity_eb', function () {
    return view('eRKL.etnicity_eb');
});

resources/views/layouts/_header.blade.php
<div id="header" class="header navbar-default">
    <!-- begin navbar-header -->
    <div class="navbar-header">
        <a href="{{route('dashboard.index')}}" class="navbar-brand"> <img src="{!! asset('images/logo.png') !!}" width="70%" style="padding: 5px" alt="" /></a>
        <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <!-- end navbar-header -->

    <!-- begin header navigation right -->
    <ul class="navbar-nav navbar-right">
        {{--<li>--}}
            {{--<form class="navbar-form full-width">--}}
                {{--<div class="form-group">--}}
                    {{--<input type="text" class="form-control" placeholder="Enter keyword" />--}}
                    {{--<button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>--}}
                {{--</div>--}}
            {{--</form>--}}
        {{--</li>--}}
        {{--<li class="dropdown">--}}
            {{--<a href="javascript:;" data-toggle="dropdown" class="dropdown-toggle f-s-14">--}}
                {{--<i class="fa fa-bell"></i>--}}
                {{--<span class="label">5</span>--}}
            {{--</a>--}}
            {{--<ul class="dropdown-menu media-list pull-right">--}}
                {{--<li class="dropdown-header">NOTIFICATIONS (5)</li>--}}
                {{--<li class="media">--}}
                    {{--<a href="javascript:;">--}}
                        {{--<div class="media-left">--}}
                            {{--<i class="fa fa-bug media-object bg-silver-darker"></i>--}}
                        {{--</div>--}}
                        {{--<div class="media-body">--}}
                            {{--<h6 class="media-heading">Server Error Reports <i class="fa fa-exclamation-circle text-danger"></i></h6>--}}
                            {{--<div class="text-muted f-s-11">3 minutes ago</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="media">--}}
                    {{--<a href="javascript:;">--}}
                        {{--<div class="media-left">--}}
                            {{--<img src="../assets/img/user/user-1.jpg" class="media-object" alt="" />--}}
                            {{--<i class="fab fa-facebook-messenger text-primary media-object-icon"></i>--}}
                        {{--</div>--}}
                        {{--<div class="media-body">--}}
                            {{--<h6 class="media-heading">John Smith</h6>--}}
                            {{--<p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>--}}
                            {{--<div class="text-muted f-s-11">25 minutes ago</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="media">--}}
                    {{--<a href="javascript:;">--}}
                        {{--<div class="media-left">--}}
                            {{--<img src="../assets/img/user/user-2.jpg" class="media-object" alt="" />--}}
                            {{--<i class="fab fa-facebook-messenger text-primary media-object-icon"></i>--}}
                        {{--</div>--}}
                        {{--<div class="media-body">--}}
                            {{--<h6 class="media-heading">Olivia</h6>--}}
                            {{--<p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>--}}
                            {{--<div class="text-muted f-s-11">35 minutes ago</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="media">--}}
                    {{--<a href="javascript:;">--}}
                        {{--<div class="media-left">--}}
                            {{--<i class="fa fa-plus media-object bg-silver-darker"></i>--}}
                        {{--</div>--}}
                        {{--<div class="media-body">--}}
                            {{--<h6 class="media-heading"> New User Registered</h6>--}}
                            {{--<div class="text-muted f-s-11">1 hour ago</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="media">--}}
                    {{--<a href="javascript:;">--}}
                        {{--<div class="media-left">--}}
                            {{--<i class="fa fa-envelope media-object bg-silver-darker"></i>--}}
                            {{--<i class="fab fa-google text-warning media-object-icon f-s-14"></i>--}}
                        {{--</div>--}}
                        {{--<div class="media-body">--}}
                            {{--<h6 class="media-heading"> New Email From John</h6>--}}
                            {{--<div class="text-muted f-s-11">2 hour ago</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="dropdown-footer text-center">--}}
                    {{--<a href="javascript:;">View more</a>--}}
                {{--</li>--}}
            {{--</ul>--}}
        {{--</li>--}}
        <li class="dropdown navbar-user">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                <img src="http://via.placeholder.com/50x50" alt="" />
                {{-- <span class="hidden-xs">{{auth()->user()->name}}</span> <b class="caret"></b> --}}
            </a>
            <ul class="dropdown-menu">
                <li class="arrow"></li>
                {{--<li><a href="javascript:;">Edit Profile</a></li>--}}
                {{--<li><a href="javascript:;"><span class="badge badge-danger pull-right">2</span> Inbox</a></li>--}}
                {{--<li><a href="javascript:;">Calendar</a></li>--}}
                {{--<li><a href="javascript:;">Setting</a></li>--}}
                <li class="divider"></li>
                <li><a href="{{route('logout')}}">Log Keluar</a></li>
            </ul>
        </li>
    </ul>
    <!-- end header navigation right -->
</div>

resources/views/layouts/_sidebar.blade.php
<div id="sidebar" class="sidebar">
    <!-- begin sidebar scrollbar -->
    <div data-scrollbar="true" data-height="100%">
        <!-- begin sidebar user -->
        {{--<ul class="nav">--}}
            {{--<li class="nav-profile">--}}
                {{--<a href="javascript:;" data-toggle="nav-profile">--}}
                    {{--<div class="cover with-shadow"></div>--}}
                    {{--<div class="image">--}}
                        {{--<img src="../assets/img/user/user-13.jpg" alt="" />--}}
                    {{--</div>--}}
                    {{--<div class="info">--}}
                        {{--<b class="caret pull-right"></b>--}}
                        {{--Sean Ngu--}}
                        {{--<small>Front end developer</small>--}}
                    {{--</div>--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<ul class="nav nav-profile">--}}
                    {{--<li><a href="javascript:;"><i class="fa fa-cog"></i> Settings</a></li>--}}
                    {{--<li><a href="javascript:;"><i class="fa fa-pencil-alt"></i> Send Feedback</a></li>--}}
                    {{--<li><a href="javascript:;"><i class="fa fa-question-circle"></i> Helps</a></li>--}}
                {{--</ul>--}}
            {{--</li>--}}
        {{--</ul>--}}
        <!-- end sidebar user -->
        <!-- begin sidebar nav -->
        <ul class="nav">
            <li class="nav-header">Navigasi</li>
            <li class="has-sub {{request()->segment(2)=='dashboard'?'active':''}}"><a href="{{route('dashboard.index')}}"><i class="fa fa-home"></i> <span>Papan pemuka</span></a></li>
            <li class="has-sub {{request()->segment(2)=='edoc1-management'?'active':''}}"><a href="{{route('census-operation.edoc1-management.edoc1-verifications.index')}}"><i class="fa fa-file-pdf"></i> <span>Pengurusan eDoc1</span></a></li>
            {{--<li class="has-sub {{request()->segment(2)=='products'?'active':''}}"><a href="{{route('control-panel.products.index')}}"><i class="fa fa-list"></i> <span>Product</span></a></li>--}}
            {{--<li class="has-sub {{request()->segment(2)=='inquiries'?'active':''}}"><a href="{{route('control-panel.inquiries.index')}}"><i class="fa fa-list"></i> <span>Inquiry</span></a></li>--}}
            {{--<li class="has-sub {{request()->segment(2)=='credit-packages'?'active':''}}"><a href="{{route('control-panel.credit-packages.index')}}"><i class="fa fa-list"></i> <span>Credit Package</span></a></li>--}}
            {{--<li class="has-sub {{request()->segment(2)=='order-histories'?'active':''}}"><a href="{{route('control-panel.order-histories.index')}}"><i class="fa fa-list"></i> <span>Order History</span></a></li>--}}
            {{--@if(auth()->user()->hasRole('admin'))--}}
                {{--<li class="has-sub {{request()->segment(2)=='users'?'active':''}}"><a href="{{route('control-panel.users.index')}}"><i class="fa fa-users"></i> <span>User</span></a></li>--}}
                {{--<li class="has-sub {{request()->segment(2)=='brands'?'active':''}}"><a href="{{route('control-panel.brands.index')}}"><i class="fa fa-cogs"></i> <span>Brand</span></a></li>--}}
                {{--<li class="has-sub {{request()->segment(2)=='merchants'?'active':''}}"><a href="{{route('control-panel.merchants.index')}}"><i class="fa fa-users"></i> <span>Merchant</span></a></li>--}}
                {{--<li class="has-sub {{request()->segment(2)=='product-categories'?'active':''}}"><a href="{{route('control-panel.product-categories.index')}}"><i class="fa fa-cogs"></i> <span>Product Category</span></a></li>--}}
                {{--<li class="has-sub {{request()->segment(2)=='product-subscriptions'?'active':''}}"><a href="{{route('control-panel.product-subscriptions.index')}}"><i class="fa fa-cogs"></i> <span>Product Subscription</span></a></li>--}}
                {{--<li class="has-sub {{request()->segment(2)=='subscription-plans'?'active':''}}"><a href="{{route('control-panel.subscription-plans.index')}}"><i class="fa fa-cogs"></i> <span>Subscription Plan</span></a></li>--}}
            {{--@endif--}}

            {{--<li class="has-sub"><a href="{{route('home.index')}}" target="_blank"><i class="fa fa-globe"></i> <span>Go To Website</span></a></li>--}}

            <li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
            <!-- end sidebar minify button -->
        </ul>
        <!-- end sidebar nav -->
    </div>
    <!-- end sidebar scrollbar -->
</div>
<div class="sidebar-bg"></div>

resources/views/layouts/_top_menu.blade.php
<div id="top-menu" class="top-menu">
    <!-- begin top-menu nav -->
    <ul class="nav">
        <li class="has-sub {{request()->segment(2)=='dashboard'?'active':''}}"><a href="{{route('control-panel.dashboard.index')}}"><i class="fa fa-home"></i> <span>Dashboard</span></a></li>
        <li class="has-sub {{request()->segment(2)=='products'?'active':''}}"><a href="{{route('control-panel.products.index')}}"><i class="fa fa-list"></i> <span>Product</span></a></li>
        <li class="has-sub {{request()->segment(2)=='inquiries'?'active':''}}"><a href="{{route('control-panel.inquiries.index')}}"><i class="fa fa-list"></i> <span>Inquiry</span></a></li>
        @if(auth()->user()->hasRole('admin'))
        <li class="has-sub {{request()->segment(2)=='users'?'active':''}}"><a href="{{route('control-panel.users.index')}}"><i class="fa fa-users"></i> <span>User</span></a></li>
        <li class="has-sub {{request()->segment(2)=='brands'?'active':''}}"><a href="{{route('control-panel.brands.index')}}"><i class="fa fa-cogs"></i> <span>Brand</span></a></li>
        <li class="has-sub {{request()->segment(2)=='merchants'?'active':''}}"><a href="{{route('control-panel.merchants.index')}}"><i class="fa fa-users"></i> <span>Merchant</span></a></li>
        <li class="has-sub {{request()->segment(2)=='product-categories'?'active':''}}"><a href="{{route('control-panel.product-categories.index')}}"><i class="fa fa-cogs"></i> <span>Product Category</span></a></li>
        <li class="has-sub {{request()->segment(2)=='product-subscriptions'?'active':''}}"><a href="{{route('control-panel.product-subscriptions.index')}}"><i class="fa fa-cogs"></i> <span>Product Subscription</span></a></li>
        @endif

        <li class="has-sub"><a href="{{route('home.index')}}" target="_blank"><i class="fa fa-globe"></i> <span>Go To Website</span></a></li>

    </ul>
    <!-- end top-menu nav -->
</div>